### ISSUE TITLE
[Models] Attendance

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler-server#3]
- Make a MongoDB model (schema) to store Attendance for courses
- Make this under `/Models` directory
- Proposed attributes are: `_id`, `total_days`, `attended_days`, `courseID` (this attribute would refer to another Schema Course.js), `userID` (this would also be an ID referred from User.js schema)

**Comment by Abhishek-Srivas** [comment]
I have done a recent project as a Backend Developer using Node, Express and  MongoDB and had made a E-Learning platform. I want to work on this Please assign this issue to me

**Comment by meet59patel** [comment]
@AbhishekSrivas114319 Thanks for your interest but this project is particularly for SLoP participants for now. 

Semester Long Projects by DSC, DAIICT | https://slop.dscdaiict.in/

**Comment by Abhishek-Srivas** [comment]
Ok sir

**Comment by Harsh-Modi278** [comment]
Can you please assign this issue to me?

**Comment by meet59patel** [comment]
@Harsh-Modi278 assigned
