### ISSUE TITLE
[Models] Assignment schema

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/schooler-server#4]
- Make a MongoDB model (schema) to store Assignments for courses
- Make this under `/Models` directory
- Proposed attributes are: 
  - `_id`, 
  - `title`, 
  - `description`, 
  - `courseID` (this attribute would refer to another Schema Course.js), 
  - `userID` (this would also be an ID referred from User.js schema), 
  - `links` (this would be an array)

**Comment by Abhishek-Srivas** [comment]
I have recently worked on a project as a Backend Developer using Node, Express & MongoDB and made a E-learning website. I want to work on this can you please assign this project to me

**Comment by Harsh-Modi278** [comment]
Can you please assign this issue to me?

**Comment by meet59patel** [comment]
@Harsh-Modi278 assigned
